### PR TITLE
Parallel upload for SNP data

### PR DESCRIPTION
**Pull request by baroleg**

### CODE REVIEW

**Comment by xuatiknc** [comment]
Are you sure parallel execution really helps?

Because I want to remove all "PARALLEL" hints and everything else related to parallel executions from the code. I consider this stuff harmful. Of course there are legitimate uses for parallel executions but the database should be designed for that. It should never be used as a hack.

**Comment by mirasrael** [comment]
Yes, it really helps. For our testing we found for PostgreSQL it improves load speed 4 times (2 minutes instead of 8 for test sample). Because for SNP we may have a lot of data (something like 1-2Gb in data files) it will greatly improve initial load speed.
Using parallel uploading here is relatively safe because we are doing only insert operation into temp table. Other part of upload (in db procedure) rest without changes.
To be paranoid we can disable parallel upload by default and make it available via option.

**Comment by xuatiknc** [comment]
Ok, then.

**Comment by mirasrael** [comment]
Merged

**Pull request closed without merging**
